### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by satrox28** [khicks/linuxacademy-dl#1]
Launching Chrome...
Logging in...
Login success.
Loading course...
Traceback (most recent call last):
  File "./linux.py", line 202, in <module>
    main()
  File "./linux.py", line 187, in main
    course_title = load_course(driver, args)
  File "./linux.py", line 119, in load_course
    course_title = driver.find_elements_by_class_name('course-title')[0].text
IndexError: list index out of range

I was trying for id=228 and getting the above error. It is working for other courses. Can you help me. 

Thanks for creating this awesome script.

**Comment by khicks** [comment]
Hey there, I'm glad you like the script and sorry to hear you're having issues.

I'm not able to reproduce the issue, but could you try going to [line 115](https://github.com/khicks/linuxacademy-dl/blob/702835d0bfdf87752529103f3604e3bd783304e5/linuxacademy-dl.py#L115) and increasing the value from 5 to 15? I'm wondering if the page hasn't had time to load before attempting to grab the title.

**Comment by satrox28** [comment]
As suggested, tried updating to 15 and got the same error. Can you try for the below link and let me know,

# ./linux.py -u username -p password -c cookies.txt https://linuxacademy.com/cp/modules/view/id/228
Launching Chrome...
Logging in...
Login success.
Loading course...
Traceback (most recent call last):
  File "./linux.py", line 202, in <module>
    main()
  File "./linux.py", line 187, in main
    course_title = load_course(driver, args)
  File "./linux.py", line 119, in load_course
    course_title = driver.find_elements_by_class_name('course-title')[0].text
IndexError: list index out of range

**Comment by satrox28** [comment]
script not working now, can you test it.

**Comment by satrox28** [comment]
Seeing below message all courses.

id-228
Launching Chrome...
Logging in...
Login success.
Loading course...
Course title: COURSE-ID-228
Fetching video list...
Found 0 video.
Done.

**Comment by khicks** [comment]
Can you try a fresh Ubuntu install and going through the installation steps?

**Comment by satrox28** [comment]
Hi,

I tried it on a new ubuntu machine still same error. Can you try it your side on a different machine.

**Comment by satrox28** [comment]
Hi,
It's working fine thanks, had tried with incorrect url earlier. thanks for all your work. :)
